# Generated by Django 5.2.4 on 2026-05-25 11:07

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categorychildimage_categoryparentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryparentimage',
            name='parent',
        ),
        migrations.AlterField(
            model_name='categorychild',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.unique_category_image),
        ),
        migrations.AlterField(
            model_name='categoryparent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.unique_category_image),
        ),
        migrations.DeleteModel(
            name='CategoryChildImage',
        ),
        migrations.DeleteModel(
            name='CategoryParentImage',
        ),
    ]
