# Generated by Django 5.2.4 on 2026-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
