# Generated by Django 5.2.4 on 2026-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='more_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
