# Generated by Django 5.2.4 on 2026-08-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'اکبند'), ('used', 'دست دوم')], default='new', max_length=20)),
                ('warranty', models.CharField(choices=[('no_warranty', 'بدون گارانتی'), ('official', 'گارانتی رسمی'), ('store', 'گارانتی فروشگاه')], default='no_warranty', max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.products')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
    ]
