# Generated by Django 6.0.5 on 2026-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productvariant_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='warranty_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
