# Generated by Django 6.0.5 on 2026-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
