import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/Components/Header/Header";
import Footer from "@/app/Components/Footer/Footer";
import { AuthProvider } from "@/app/Context/Context";
import Contentbox from "./ContentBox/Contentbox";
import Toast from "./ToastError/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Header />
          <Contentbox />
          <Toast />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
