# Generated by Django 6.0.5 on 2026-08-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_newsgallery_tutorialgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='newsgallery',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='education.news'),
        ),
    ]
