# Generated by Django 6.1.1 on 2026-09-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_news_tags_tutorial_tags_alter_newsgallery_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialgallery',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='education.tutorial'),
        ),
    ]
